# Generated by Django 4.0.2 on 2022-06-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('idPet', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de mascota')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre mascota')),
            ],
        ),
    ]
